---
# tasks file for passwordless

- name: Get Current User
  command: whoami
  register: current_user
  changed_when: false

- name: Add Passwordless Sudo
  become: true
  lineinfile:
    path: "/etc/sudoers.d/{{ current_user.stdout }}-nopasswd"
    create: true
    state: present
    line: "{{ current_user.stdout }} ALL=(ALL) NOPASSWD:ALL"
    validate: 'visudo -cf %s'
