---
# tasks file for reboot

- name: Check For Reboot
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot
  reboot:
  when: reboot_required_file.stat.exists == true
