---
# tasks file for dns

- name: Create Resolve Symlink
  become: true
  file:
    state: link
    src: /run/systemd/resolve/resolv.conf
    path: /etc/resolv.conf

- name: Disable DNS Stub Listener
  become: true
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: "#?DNSStubListener=yes"
    line: DNSStubListener=no
  register: resolvedconf

- name: Restart Systemd-Resolved
  become: true
  service:
    name: systemd-resolved
    state: restarted
  when: resolvedconf.changed

- block:
  - name: Enable IPV4 Forwarding
    become: true
    lineinfile:
      line: 'net.ipv4.ip_forward = 1'
      path: /etc/sysctl.conf
    changed_when: false

  - name: Enable IPV6 Forwarding
    become: true
    lineinfile:
      line: 'net.ipv6.conf.all.forwarding = 1'
      path: /etc/sysctl.conf
    changed_when: false

  - name: Reload IP Configs
    become: true
    shell:
      cmd: sysctl -p /etc/sysctl.conf
    changed_when: false
  when: "'vpn' in group_names"
