---
# tasks file for dns

- name: Create DNS File
  file:
    path: .dns
    state: touch
    mode: 600
  when: "'dns' in group_names"

- name: Check for DNS File
  stat:
    path: .dns
  register: dns

- block:
  - name: Create VPN File
    file:
      path: .vpn
      state: touch
      mode: 600
    when: "'vpn' in group_names"

  - name: Check for VPN File
    stat:
      path: .vpn
    register: vpn

  - name: Create Resolve Symlink
    become: true
    file:
      state: link
      src: /run/systemd/resolve/resolv.conf
      path: /etc/resolv.conf

  - name: Disable DNS Stub Listener
    become: true
    lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: "#?DNSStubListener=yes"
      line: DNSStubListener=no
    register: resolvedconf

  - name: Restart Systemd-Resolved
    become: true
    service:
      name: systemd-resolved
      state: restarted
    when: resolvedconf.changed

  - block:
    - name: Enable IPV4 Forwarding
      become: true
      lineinfile:
        line: 'net.ipv4.ip_forward = 1'
        path: /etc/sysctl.conf
      changed_when: false

    - name: Enable IPV6 Forwarding
      become: true
      lineinfile:
        line: 'net.ipv6.conf.all.forwarding = 1'
        path: /etc/sysctl.conf
      changed_when: false

    - name: Reload IP Configs
      become: true
      shell:
        cmd: sysctl -p /etc/sysctl.conf
      changed_when: false
    when: "vpn.stat.exists"
  when: "dns.stat.exists"
