---
- name: Lab
  hosts: all
  tasks:
    - name: Import Security Role
      import_role:
        name: nickconway.shared.security

    - name: Import Update Role
      import_role:
        name: nickconway.shared.update

    - name: Import Reboot
      import_role:
        name: reboot

    - name: Import Cron Role
      import_role:
        name: nickconway.shared.cron

    - name: Import Shared Programs Role
      import_role:
        name: nickconway.shared.programs

    - name: Import Programs Role
      import_role:
        name: programs

    - name: Import VPN Role
      import_role:
        name: nickconway.shared.vpn
      when: "'vpn' in group_names"

    - name: Import YADM Role
      import_role:
        name: nickconway.shared.yadm

    - name: Import WSL Role
      import_role:
        name: nickconway.shared.wsl

    - name: Import DNS Role
      import_role:
        name: dns
      when: "'dns' in group_names"
