---
- name: Lab
  hosts: all
  tasks:
    - name: Create Server File
      file:
        path: .server
        state: touch
        mode: 600
      when: "'servers' in group_names"

    - name: Create Work File
      file:
        path: .work
        state: touch
        mode: 600
      when: "'work' in group_names"

    - name: Import Security Role
      import_role:
        name: nickconway.shared.security

    - name: Import Update Role
      import_role:
        name: nickconway.shared.update

    - name: Import Reboot
      import_role:
        name: reboot

    - name: Import Cron Role
      import_role:
        name: nickconway.shared.cron

    - name: Import Shared Programs Role
      import_role:
        name: nickconway.shared.programs

    - name: Import Programs Role
      import_role:
        name: programs

    - name: Import VPN Role
      import_role:
        name: nickconway.shared.vpn

    - name: Import YADM Role
      import_role:
        name: nickconway.shared.yadm

    - name: Import Passwordless Role
      import_role:
        name: nickconway.shared.passwordless

    - name: Import WSL Role
      import_role:
        name: nickconway.shared.wsl

    - name: Import DNS Role
      import_role:
        name: dns
