#!/bin/bash

if [ "${PAM_TYPE}" = "open_session" ]; then
    echo "${PAM_RHOST}" | grep -qE '^(10\.)'
    if [[ "$?" -ne 0 ]]; then
        curl -d "SSH login on $(hostname): ${PAM_USER} from ${PAM_RHOST}" https://ntfy.conway.dev/ssh -H "Authorization: Bearer {{ ntfy_ssh_token }}" || echo "Failed to notify of ssh login"
    fi
fi
